name: build artifacts
on: [push]
jobs:
  build-linux-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Jimver/cuda-toolkit@v0.2.4
        id: cuda-toolkit
        with:
          cuda: '11.4.0'
      - run: sudo apt-get install -y build-essential libuv1-dev
      - run: make linux-gpu
